In [2]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [9]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [4]:
arr4 = np.array([1,2,'a','b',0.1,0.2]) #데이터타입 동일
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [12]:
arr5 = np.array([1,2,0.3,0.4])
arr5

array([1. , 2. , 0.3, 0.4])

In [13]:
arr6 = np.array(
[[1,2,3],
[4,5,6],
[7,8,9]])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# array의 타입

In [15]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr2

array([0.1, 0.2, 0.3])

In [18]:
arr2.dtype

dtype('float64')

In [19]:
print(arr3.dtype)
arr3

<U1


array(['a', 'b', 'c'], dtype='<U1')

In [20]:
print(arr4.dtype)
arr4

<U11


array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [21]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

# shape

In [22]:
arr5

array([1. , 2. , 0.3, 0.4])

In [23]:
arr5.shape

(4,)

In [24]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr6.shape

(3, 3)

# arrage

In [30]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr2 = np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
arr3 = np.arange(0,5,0.5)
arr3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
arr4 = np.arange(3,100,3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

# linspace

In [22]:
temp=np.linspace(0,5,10)
temp

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
for idx in range(1,len(temp)):
    print(temp[idx]-temp[idx-1])

0.5555555555555556
0.5555555555555556
0.5555555555555556
0.5555555555555556
0.5555555555555554
0.5555555555555558
0.5555555555555558
0.5555555555555554
0.5555555555555554


# reshape(배열의 형태변환)

In [38]:
arr = np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [39]:
arr.shape

(36,)

In [42]:
arr2 = arr.reshape(12,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [44]:
#3 dimension
arr3 = arr.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [47]:
print(arr1.shape)
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr1.shape=(5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
# -1 shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [52]:
arr3.reshape(-1,12) # 행열중 하나만 선택했을 때 -1 (모르는 값) 사용

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [53]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [54]:
arr3.reshape(4,-1,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

# astype - 배열의 dtype 변환

In [25]:
arr1 = np.arange(5)
arr2 = np.arange(0.0,0.5,0.1)
arr1,arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [56]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [26]:
#int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [60]:
# float -> char
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


# rand

In [5]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [9]:
np.random.rand(3,3)

array([[0.14035078, 0.87008726, 0.47360805],
       [0.80091075, 0.52047748, 0.67887953],
       [0.72063265, 0.58201979, 0.53737323]])

In [4]:
np.random.rand(4,3,2) #z,x,y

array([[[0.57304271, 0.66556972],
        [0.86701404, 0.31371547],
        [0.39966791, 0.56775204]],

       [[0.72163861, 0.31357592],
        [0.26589542, 0.1632555 ],
        [0.17978194, 0.88478894]],

       [[0.20407166, 0.60109271],
        [0.43883921, 0.10381827],
        [0.44765863, 0.11902873]],

       [[0.47314086, 0.72510745],
        [0.33887438, 0.65440899],
        [0.33802026, 0.16933566]]])

### randint

In [10]:
np.random.randint(-5,2,(3,3))

array([[-5, -3, -1],
       [-2,  1, -2],
       [-3, -1, -3]])

In [13]:
np.random.randn(2,5)

array([[-0.74385608, -2.5174371 , -1.50709602,  1.14907613, -1.19357825],
       [ 1.14104245,  1.50944508,  1.06777513, -0.68658948,  0.01487332]])

# array의 indexing, Slicing

In [72]:
arr1 = np.arange(0,100,10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [75]:
arr1[0] , arr1[-1], arr1[5]

(0.0, 90.0, 50.0)

In [76]:
arr1[:],arr1[4:],arr1[1:8]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70.]))

In [77]:
arr1[::2],arr1[::3]

(array([ 0., 20., 40., 60., 80.]), array([ 0., 30., 60., 90.]))

### n - Dim Array Indexing, Slicing

In [83]:
#2차원 배열 : 0~23 , (8,3) dtype = float
arr2 = np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [84]:
arr2[0]

array([0., 1., 2.])

In [89]:
print(arr2[3][1]) #성능이 조금 느려요
print(arr2[3,1])

10.0
10.0


In [98]:
print(arr2[3,1:])
print(arr2[3:, 1:])
print(arr2[::2,:])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [100]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [103]:
print(arr2[[0,5,3]])
print('-'*20)
print(arr2[[0,5,3],[1]])

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
--------------------
[ 1. 16. 10.]


In [106]:
arr2>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [105]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [108]:
arr2 [arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

In [11]:
arr1 = np.arange(36).reshape(-1,3)
print(arr1.shape)

(12, 3)


### numpy의 상수

In [113]:
arr = np.array([1,2,3,np.nan,np.inf,-np.inf])
print(arr)
print("dtype",arr.dtype)

[  1.   2.   3.  nan  inf -inf]
dtype float64


## arr의 연산

In [116]:
arr1= np.arange(0,10,1)
arr2= np.arange(1,0,-0.1)
arr1,arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [119]:
# array와 scalar 연산
arr1 + 1,arr1 + [1,1,1,1,1,1,1,1,1,1]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [122]:
print(arr1-1)
print(arr1*10)
print(arr1/10)
print(arr1**2)
print(arr1%2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [124]:
arr1+arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [127]:
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1** arr2)
print(arr1 % arr2)

[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [129]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [130]:
arr1 > arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [132]:
# 0행렬
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [134]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##  일행렬

In [136]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [139]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 단위행렬

In [140]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [141]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.eye(2),np.eye(3)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# 통계를 위한 연산

In [144]:
arr1 = np.arange(1,11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [145]:
arr1.sum()

55.0

In [148]:
arr1.sum(axis=0) # axis가 0 일 경우 column , 1일 경우 row

array([25., 30.])

In [149]:
arr1.sum(axis=1)

array([ 3.,  7., 11., 15., 19.])

## mean

In [155]:
arr1.mean()

5.5

In [156]:
arr1.mean(axis=0)

array([5., 6.])

In [157]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

## var

In [159]:
arr1.var()

8.25

In [161]:
arr1.var(axis=0)

array([8., 8.])

In [166]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

## std

In [163]:
arr1.std()

2.8722813232690143

In [164]:
arr1.std(axis=0)

array([2.82842712, 2.82842712])

In [165]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

## min

In [175]:
print(arr1.min())
print(arr1.min(axis=0)) # 열
print(arr1.min(axis=1)) #행

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


## max

In [176]:
arr1.max(axis=0)

array([ 9., 10.])

In [177]:
arr1.max(axis=1)

array([ 2.,  4.,  6.,  8., 10.])

## cumsum 누적합

In [178]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [179]:
arr1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [180]:
arr1.cumsum(axis=0)

array([[ 1.,  2.],
       [ 4.,  6.],
       [ 9., 12.],
       [16., 20.],
       [25., 30.]])

In [181]:
arr1.cumsum(axis=1)

array([[ 1.,  3.],
       [ 3.,  7.],
       [ 5., 11.],
       [ 7., 15.],
       [ 9., 19.]])

## cumprod

In [184]:
arr1.cumprod()

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [185]:
arr1.cumprod(axis=0)

array([[1.00e+00, 2.00e+00],
       [3.00e+00, 8.00e+00],
       [1.50e+01, 4.80e+01],
       [1.05e+02, 3.84e+02],
       [9.45e+02, 3.84e+03]])

In [186]:
arr1.cumprod(axis=1)

array([[ 1.,  2.],
       [ 3., 12.],
       [ 5., 30.],
       [ 7., 56.],
       [ 9., 90.]])

## sqrt, log, exp

In [172]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [169]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [187]:
np.exp(arr1) #e+00 : 10^00승

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

## 행렬곱

In [195]:
arr1 = np.arange(1,7).astype(np.float64).reshape(2,3)
arr2 = np.arange(6,0,-1.0).astype(np.float64).reshape(3,2)
arr1,arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [190]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [191]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [193]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [194]:
np.matmul(arr1,arr2)

array([[20., 14.],
       [56., 41.]])

## 전치

In [197]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [201]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [202]:
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [203]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [205]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [206]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

In [208]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [210]:
arr1 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [211]:
arr2 = np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [212]:
arr1.dot(arr2) # e-16 : 0으로 간주 (굉장히 작은 수)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [213]:
arr2.dot(arr1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## concat

In [215]:
arr1= np.arange(4).reshape(2,2)
arr2 = np.arange(0,40,10).reshape(2,2)
arr1,arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [216]:
np.concatenate((arr1,arr2),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [217]:
np.concatenate((arr1,arr2),axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [218]:
# np.c_
np.c_[arr1,arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# 연습문제

In [288]:
arr=np.zeros(10)
#arr[[4,5]]=1
arr[4:6]=1
arr=arr.reshape(5,2)
arr

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [289]:
arr = np.arange(10,30,2)
a=np.arange(1.0,2.0,0.1)
print(arr+a)
print(arr-a)
print(arr*a)
print(arr/a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


In [293]:
arr = np.linspace(1,100,10) #균등하게 차이 arange와 차이점 파악하자
print(arr)
print(arr.sum()) #합
print(arr.mean()) #평균
print(arr.std()) #표준편차
print(arr.var()) #분산
print(arr.min())#최소값
print(arr.max())#최대값
print(arr.cumsum())#누적합
print(arr.cumprod())#누적곱

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
505.0
50.5
31.595094555959157
998.25
1.0
100.0
[  1.  13.  36.  70. 115. 171. 238. 316. 405. 505.]
[1.00000000e+00 1.20000000e+01 2.76000000e+02 9.38400000e+03
 4.22280000e+05 2.36476800e+07 1.58439456e+09 1.23582776e+11
 1.09988670e+13 1.09988670e+15]


In [305]:
np.random.seed(42) # 42번째 배열에서만 random을 꺼내주세요
np.random.rand(3,3)*10

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

In [295]:
np.random.randint(0,10,(3,3))

array([[3, 1, 0],
       [8, 1, 3],
       [3, 7, 9]])

In [335]:
arr1 = np.random.randn(5,2)
print(arr1)
#print(arr1.mean(axis=0))
#print(arr1.std(axis=0))
arr2= (arr1-arr1.mean(axis=0))/arr1.std(axis=0)
print(arr2.mean(),arr2.std(),arr2.var())

[[ 2.77831304  1.19363972]
 [ 0.21863832  0.88176104]
 [-1.00908534 -1.58329421]
 [ 0.77370042 -0.53814166]
 [-1.3466781  -0.88059127]]
-4.4408920985006264e-17 1.0 1.0


In [338]:
(arr1-arr1.min(axis=0)) / (arr1.max()-arr1.min(axis=0))

array([[1.        , 0.63667675],
       [0.37947146, 0.5651713 ],
       [0.08184084, 0.        ],
       [0.51403226, 0.23962555],
       [0.        , 0.16111101]])

# 강사님 코드

In [315]:
arr1 = np.linspace(-1000,1000,5)
arr1=arr1.reshape(5,-1)
arr2 = np.linspace(0,10,5)
arr2 = arr2.reshape(5,-1)
arr3= np.concatenate((arr1,arr2),axis=1)
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [317]:
arr1.std(), arr2.std()

(707.1067811865476, 3.5355339059327378)

In [323]:
arr4=(arr3- arr3.mean(axis=0))/arr3.std(axis=0)
arr4

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [324]:
arr4.mean(),arr4.std(),arr4.var()

(0.0, 0.9999999999999999, 0.9999999999999998)

In [327]:
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [330]:
arr5 = (arr3-arr3.min(axis=0))/(arr3.max(axis=0) - arr3.min(axis=0))
arr5

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])